In [1]:
import numpy as np
import pandas as pd

In [39]:
VP = 0.4
LR = 0.2

n = 4
m = 3

b = np.array([[1/(1+n) for i in range(m) ] for j  in range(n) ])

#b = np.array([[0.2, 0.5, 0.9], [0.6, 0.2, 0.5], [0.1, 0.4, 0.7], [0.8, 0.4, 0.2]])

t =  np.array([[1 for i in range(n)] for j in range(m)])

In [40]:
b

array([[0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2]])

In [41]:
t

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
def network(inputs,b,t,epochs):
    
    B = b
    T = t
    
    for e in range(epochs):
    
        
        for ip in inputs:
            inp = ip
            sum_of_input = sum(inp)
        
            y1 = np.dot(B[:,0],inp)
            y2 = np.dot(B[:,1],inp)
            y3 = np.dot(B[:,2],inp)
        
            yarray = np.array([y1,y2,y3])
            J = np.argmax(yarray)
        
            xi = inp * t[1,:]
        
            norm_of_xi = np.sum(xi)
        
            if(norm_of_xi/sum_of_input) > VP:
            
                for i in range(4):
                    B[i][J] = (LR*xi[i])/(LR-1+norm_of_xi)
                    T[J][i] = b[i][J]
        
        
            
    
    return B,T
                
        
        
        

In [43]:
def test(inputs,B):
    cluster =[]
    for ip in inputs:
            inp = ip
            sum_of_input = sum(inp)
        
            y1 = np.dot(B[:,0],inp)
            y2 = np.dot(B[:,1],inp)
            y3 = np.dot(B[:,2],inp)
        
            yarray = np.array([y1,y2,y3])
            J = np.argmax(yarray)
            cluster.append(J)
    return cluster

In [44]:
inputs = np.array([[0,0,0,1],[0,0,1,0],[0,0,1,1],[0,1,0,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],[1,0,0,0],[1,0,0,1],[1,0,1,0]])

In [45]:
inputs

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0]])

In [46]:
trained_b ,trained_t = network(inputs,b,t,56)

In [47]:
trained_b

array([[0. , 0. , 0.2],
       [0. , 0. , 0.2],
       [1. , 1. , 0.2],
       [0. , 0. , 0.2]])

In [48]:
test(inputs,trained_b)

[2, 0, 0, 2, 2, 0, 0, 2, 2, 0]

In [49]:
inputss = np.array([[0,1,0,1],[0,1,1,0],[0,0,0,1],[0,0,1,0],[0,1,1,1],[1,0,0,0],[1,0,0,1],[1,0,1,0],[0,0,1,1],[0,1,0,0]])
test(inputss,trained_b)

[2, 0, 2, 0, 0, 2, 2, 0, 0, 2]

In [50]:
inputss = np.array([[0,1,0,1],[0,1,1,0],[0,0,0,1],[0,0,1,0],[0,1,1,1],[1,0,0,0],[1,0,0,1],[1,0,1,0],[0,0,1,1],[0,1,0,0]])
trained_b ,trained_t = network(inputss,b,t,56)
test(inputss,trained_b)

[2, 0, 2, 0, 0, 2, 2, 0, 0, 2]

In [51]:
trained_b

array([[0. , 0. , 0.2],
       [0. , 0. , 0.2],
       [1. , 1. , 0.2],
       [0. , 0. , 0.2]])