In [1]:
import numpy as np


In [2]:
input_pattern = [[1,1,-1],[1,-1,1],[-1,1,1]]
output_pattern = [[1,1],[1,-1],[-1,1]]

In [3]:
def training(input_pattern,output_pattern):
    input_size = len(input_pattern[0])
    output_size = len(output_pattern[0])
    weight_matrix = np.zeros((output_size,input_size))
    
    for i in range(len(input_pattern)):
        X = np.array(input_pattern[i])
        Y = np.array(output_pattern[i])
        weight_matrix += np.outer(Y,X)
    return weight_matrix

In [8]:
def recall_output(trained_weight,input_pattern):
    input_pattern = np.array(input_pattern)
    output_size = trained_weight.shape[0]
    output_pattern = np.zeros(output_size)
    
    for i in range(output_size):
        activation = np.dot(trained_weight[i,:] , input_pattern)
        output_pattern[i] = np.sign(activation)
        
    return output_pattern
    

In [9]:
def recall_input(trained_weight,output_pattern):
    output_pattern = np.array(output_pattern)
    input_size = trained_weight.shape[1]
    input_pattern = np.zeros(input_size)
    
    for i in range(input_size):
        activation = np.sum(trained_weight[:,i]*output_pattern)
        #input_pattern[i] = np.sign(activation)
        
        if(activation>=0):
            input_pattern[i]=1
        elif(activation<0):
            input_pattern[i]=-1
        
    return input_pattern

In [10]:
trained_weight = training(input_pattern,output_pattern)
trained_weight

array([[ 3., -1., -1.],
       [-1.,  3., -1.]])

In [11]:
recall_output(trained_weight,[1,-1,1])

array([ 1., -1.])

In [45]:
recall_output(trained_weight,[-1,1,1])

array([-1.,  1.])

In [46]:
recall_output(trained_weight,[1,1,-1])

array([1., 1.])

In [47]:
recall_input(trained_weight,[1,-1])

array([ 1., -1.,  1.])

In [48]:
recall_input(trained_weight,[1,1])

array([ 1.,  1., -1.])

In [49]:
recall_input(trained_weight,[-1,1])

array([-1.,  1.,  1.])